### ISSUE TITLE
-sh: /usr/local/bin/lsix: Permission denied

### ISSUE THREAD

**Issue by ghoshaw** [hackerb9/lsix#12]
Hi, I put the file in /usr/local/bin, and it show the error that permission denied. I used this in Mac.

**Comment by SijiaDavis** [comment]
@ghoshaw 
try `chmod 755 lsix`, it will make it executable

**Comment by hackerb9** [comment]
SijiaDavis is correct. Although, if the file is in /usr/local/bin, you can do:

    chmod 755 /usr/local/bin/lsix

and then run `lsix`.
