### ISSUE TITLE
Lots of symbols instead of an image

### ISSUE THREAD

**Issue by talentlessguy** [hackerb9/lsix#19]
Also font errors?

```bash
montage: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1383.  Y\xM]Y\UYXuiCWG@I?C#1!6?G?CG??C!4?g??O?G_#2!13?o!5?GOCBwUXq?ISHG?G?AoOcGA?iU?R_AoLa?G?OAG@@A???@C??gFpcOcIb???KNGvzvA_A?z]~sCg_~L~Kx_??ZdyHQPGogS@?o~PuFk
```

**Imagemagick** version: 7.0.8
**Fish** version: 3.0.1
**OS**: Android 6.0 armv7l (Termux)
**Kernel**: 3.18.19

**Comment by hackerb9** [comment]
What terminal program are you using? It sounds like your terminal does not understand SIXEL escape sequences.

**Comment by talentlessguy** [comment]
@hackerb9 OK, yes, my terminal doesn't support sixel :(

**Comment by hackerb9** [comment]
Okay, so not an lsix bug. Are you running Android/Linux on a tablet? There may be other terminals that do handle sixel. Or leave a bug report for the terminal program you're using to let them know sixel is a good feature to add.

**Comment by talentlessguy** [comment]
@hackerb9 [Yeah, someone already did a feature request so there's no problem with lsix](https://github.com/termux/termux-app/issues/142)
