### ISSUE TITLE
Terminal in vim: Error: Your terminal does not appear to support sixel graphics.

### ISSUE THREAD

**Issue by Tanath** [hackerb9/lsix#21]
If you run `:terminal` in vim, you get what seems to be a fully-functional terminal, though `lsix` claims it won't work. `echo $TERM` reports `xterm-256color`. I've tested this in `xterm` where `lsix` otherwise works.

I get the same issue in `guake` directly, though that's likely a separate issue.

**Comment by hackerb9** [comment]
This sounds like a bug to report to the vim team. `lsix` does not look at the TERM variable. Instead it queries the terminal to find out if it is sixel capable; that response is up to vim. Are you able to view sixel images within vim? For example, if you do this:

    convert foo.jpg -geometry 800x480 sixel:-

are you able to see an image?

**Comment by Tanath** [comment]
Ah, nothing happens, it just exits. I guess it is not as fully functional as it seemed.

**Comment by hackerb9** [comment]
Thanks for letting me know. You can file a bug report with the vim project asking for them to add sixel support. After all, if emacs can show images inline, then vim should be able to as well. 😉

**Comment by LikDev-256** [comment]
Konsole also has this problem
The Command,
`convert foo.jpg -geometry 800x480 sixel:-`

Does not return anything

**Comment by hackerb9** [comment]
> Konsole also has this problem The Command, `convert foo.jpg -geometry 800x480 sixel:-`
> 
> Does not return anything

If `convert` shows nothing, then Konsole likely does not support sixel graphics. Or, it is possible that, like XTerm, it needs a command line argument to enable showing sixels. Either way, there's nothing lsix can do. Once lsix has sent the graphics to the terminal, it is up to Konsole to display them.

I suggest asking the Konsole team and community how to view sixel graphics. If they say it is supposed to work, then please do come back here and create a new bug report. If they say Konsole does not support sixels, then perhaps they can suggest a different terminal emulator that is similar.
