### ISSUE TITLE
test iTerm2

### ISSUE THREAD

**Issue by srlehn** [hackerb9/lsix#24]
iTerm2 has now sixel support https://github.com/gnachman/iTerm2/commit/0d0003d9d20b7de3a3ffd815950acb7cc9777c38.

This script should be checked if it supports this terminal too.

I personally don't have access to an Apple system.

**Comment by hackerb9** [comment]
I have a few Apple computers, but I'm pretty sure iTerm2 doesn't run on [ProDOS 2.4.2](https://prodos8.com). I'll check with the folks who write iTerm2 and see what they have to say.

**Comment by hackerb9** [comment]
Talked to the author of iterm2. It showed a bug in my code, which I've fixed. So, iterm2 can be counted as working. Thanks for the help!
