### ISSUE TITLE
Get lsix to work on ubuntu terminal?

### ISSUE THREAD

**Issue by satoshinakamotos** [hackerb9/lsix#3]
I downloaded lsix to my /usr/local/bin folder and I'm able to run the command but it returns with gibberish.

http://prntscr.com/fjbkj2

What could I be doing wrong?

**Comment by hackerb9** [comment]
Ubuntu has more than one terminal. The default terminals (gnome-terminal and lxterminal) will not work. Try running `xterm -ti vt340`. You can also use `mlterm`, but mlterm doesn't honor xterm's escape sequence to detect the palette size, so my program defaults to only 16 colors.
