### ISSUE TITLE
macOS support with brew install?

### ISSUE THREAD

**Issue by dominiw** [hackerb9/lsix#39]

**Comment by hackerb9** [comment]
That would be nice. I know nothing about brew and don't have a Mac. If someone who knows how brew works is able to get `lsix` added as a package, I'd love it.

**Comment by kidonng** [comment]
👋 I submitted lsix to Homebrew, it is available in the core tap now.

**Comment by hackerb9** [comment]
Thank you. Are there any special instructions I should have for MacOS users? For example, _“To use lsix on a Mac, you'll need to run the  ̲ ̲ ̲ ̲ ̲ ̲?̲ ̲ ̲ ̲ ̲ ̲ ̲ ̲terminal app. Use the following brew commands to install it:  ̲ ̲ ̲ ̲ ̲ ̲?̲ ̲ ̲ ̲ ̲ ̲ ̲.”_

**Comment by kidonng** [comment]
> Are there any special instructions I should have for MacOS users? For example, _“To use lsix on a Mac, you'll need to run the  ̲ ̲ ̲ ̲ ̲ ̲?̲ ̲ ̲ ̲ ̲ ̲ ̲ ̲terminal app. 

I only know that iTerm2 supports sixel. Alacritty doesn't support graphics and kitty has its own graphics protocol. These terminals are the prominent ones on macOS, so maybe just suggest using lsix in iTerm2.

> Use the following brew commands to install it:  ̲ ̲ ̲ ̲ ̲ ̲?̲ ̲ ̲ ̲ ̲ ̲ ̲.”_

Just `brew install lsix`. I think one line in the README will do.
