### ISSUE TITLE
montage: unable to read font ...

### ISSUE THREAD

**Issue by Ryuuji159** [hackerb9/lsix#5]
When executing lsix this message shows up in the output alongside the thumbnails .

>  montage: unable to read font `/home/ryuuji/.local/share/fonts/siji.pcf' @ error/annotate.c/RenderFreetype/1468.

![screenshot](https://user-images.githubusercontent.com/17039188/50461303-52110880-095c-11e9-9fae-7ff09167056f.png)

The only thing is that I'm not using that font, the one im using is the default from xterm

**Comment by Ryuuji159** [comment]
The file exists and is correct, fontconfig wont have any problem with it.

**Comment by Ryuuji159** [comment]
Im looking into it a little more and it seems to be my linux installation having some problem with imagemagik font recognition, I will have to look it up

**Comment by hackerb9** [comment]
Did you figure anything further out? What happens if you delete or move that file elsewhere?

**Comment by Ryuuji159** [comment]
I dont have any problem after moving that file somewere else, also for some reason i dont have permisions over it or over the folder where it is, so it has nothing to do with lsix and now I have a  permisions problem in my system hahaha .
