### ISSUE TITLE
Support for Alacritty

### ISSUE THREAD

**Issue by jonathf** [hackerb9/lsix#55]
Alacritty is getting support soon it seems, and there is already work available for installation.
For example https://github.com/microo8/alacritty-sixel

I tested it out and the convert example works as expected. lsix however still displays an error.

Attribute code in error message: `^[[?4;6c`.

**Comment by hackerb9** [comment]
Thank you for the report (and letting me know that Alacritty is getting support!)  I believe I've fixed the bug.  Does it work for you?

**Comment by jonathf** [comment]
Perfect!

**Comment by j4james** [comment]
FYI, I don't think Alacritty is actually planning on adding sixel any time soon. There was a sixel PR opened about a year ago, and I believe the repo linked above is just a fork with that that PR merged, but the Alacritty maintainers don't seem keen on including it in the official build.

I think their last statement on the subject was: "one of my biggest hesitations with this PR i that it is sixel based, which in my opinion is far too complicated already" (see https://github.com/alacritty/alacritty/pull/4763#issuecomment-831191000). That said, I still think there's a chance it might get merged one day, but I wouldn't hold my breath.

**Comment by jonathf** [comment]
Thanks for the info. I didn't know.

And sorry to hear that.
