### ISSUE TITLE
ERROR: montage: delegate library support not built-in

### ISSUE THREAD

**Issue by amarakon** [hackerb9/lsix#58]
On certain files, running `lsix` will still display the image but with an error message:

```
montage: delegate library support not built-in 'glasses.png' (XML) @ warning/profile.c/ValidateXMPProfile/1945.
```

How can I get rid of this error message, or at least suppress it?

**Comment by hackerb9** [comment]
That's a new one on me. Is it saying that glasses.png contains an XMP Profile that it doesn't know how to read? Weird. I wonder if that's something new in ImageMagick 7. Please send the output from `montage -version`.

**Comment by amarakon** [comment]
The issue is that I had ImageMagick compiled without XML support. I recompiled with XML support and this doesn't happen anymore.
