### ISSUE TITLE
Regression from #55: Alacritty-sixel error "mention attribute codes: ^[[?6c"

### ISSUE THREAD

**Issue by gwimm** [hackerb9/lsix#63]
# Regression from #55
The attribute code seems to have changed for [alacritty-sixel](https://github.com/microo8/alacritty-sixel) from #55's `^[[?4;6c` to simply `^[[?6c` or I might be doing something funny..

# Demo
![image](https://user-images.githubusercontent.com/34531687/214120361-223fe541-b01f-4e0c-891a-1e44cadbdd26.png)

**Comment by FergusFettes** [comment]
I also just tried this out with the alacritty branch, same result:
```
Please mention device attribute codes: ^[[?6c
```

**Comment by hackerb9** [comment]
Well, shoot. I had hoped Alacritty would have fixed this by now. Has a bug been filed with them yet?

**Comment by z3ch5** [comment]
Same error sadly.. should this be fixed on the alacritty side or here? is there a way to force/trick sixl to show images on "non supported" terminal with variable or any other way ?

**Comment by hackerb9** [comment]
Terminals tell programs what features they support. In particular, the attribute code `4`, lets programs know that the terminal can display sixels. Alacritty at one point was correctly doing that. 

There are workarounds for old, buggy terminals, but Alacritty is a modern terminal that is still developed.

**Comment by z3ch5** [comment]
yes, but I would like to point here in case the others don't know, we are here about a fork of Alacritty that supports sixel, as so far I know, there is no official way (image protocol) in Alacritty to show images, so maybe the fork of Alacritty should do the feature report

**Comment by hackerb9** [comment]
Thank you for the clarification. Yes, of course the fork should be responsible for the bug.

**Comment by FergusFettes** [comment]
Yes, I should have mentioned also. For completions sake, here is the PR: https://github.com/alacritty/alacritty/pull/4763

**Comment by prurigro** [comment]
Hey, I believe this can be closed as it was resolved in the maintained alacritty sixel fork @ https://github.com/ayosec/alacritty/tree/graphics (see https://github.com/alacritty/alacritty/pull/4763#issuecomment-1967601846 for details)

Thanks for lsix btw- it's a great tool!
