### ISSUE TITLE
Check for other animated formats

### ISSUE THREAD

**Issue by afranke** [hackerb9/lsix#67]
There is a check for gif images to only draw the first frame if no filename is given. Other animated formats such as webp fall through the cracks.

**Comment by hackerb9** [comment]
Ah! That's not good. I never did get multi-image support complete, mostly because I do not have many such files and ImageMagick can be rather persnickety about workarounds. 

Would you mind uploading a sample file and describing how you'd like lsix to behave? Thanks!

**Comment by afranke** [comment]
Sure. Had to zip it because GitHub didn’t like it otherwise.

[not_a_smart_man.zip](https://github.com/hackerb9/lsix/files/13361953/not_a_smart_man.zip)

I expect this to behave just like it does for a gif file, where it shows the first frame as if it was a still image. Here is a screenshot exhibiting the issue:

![image](https://github.com/hackerb9/lsix/assets/117241/bd2f390f-47f8-4fe8-8512-c493b9ce34b9)

Notice how there are gif files that correctly only show a single frame, and then the (attached) webp file floods the terminal.

I’m guessing there are other file extensions (apng maybe?) that should behave the same as well, but I don’t seem to have any such file.

**Comment by hackerb9** [comment]
Thanks for the sample file. It was a simple fix: just changed "gif" to "gif|webp".

**Comment by afranke** [comment]
I get *two* frames for webp files now though. 🤔

**Comment by hackerb9** [comment]
Oh. That's odd. I guess it isn't as simple of a fix as I thought.

**Comment by hackerb9** [comment]
Oh, ho! It is was a typo introduced by Github's new fancy-pants builtin code editor. I thought for such a simple change how could I go wrong? Please try it now.

**Comment by afranke** [comment]
That’ll teach you to trust fancy new tech! 😉

It works, thanks!
