### ISSUE TITLE
Non-sixel terminals

### ISSUE THREAD

**Issue by dheera** [hackerb9/lsix#72]
I wrote a library for non-sixel terminals if you'd like to use it as a fallback:

https://github.com/dheera/python-termgraphics

**Comment by hackerb9** [comment]
Thank you for the suggestion. Your library looks nice, but `lsix` uses ImageMagick for conversion. If ImageMagick were to include an ASCII/Unicode art output, similar to how it uses libsixel, then it could make sense for lsix to use it.
