### ISSUE TITLE
Create a github release.

### ISSUE THREAD

**Issue by Jens0512** [hackerb9/lsix#8]
First of all: thanks for `lsix`! It's really great.

For packaging and releasing `lsix` -- e.g. with package managers (like `pacman` and `apt-get`) -- a release is a must, sources **can not** be pulled from master, as the packagers have no control over how the master branch changes.

Luckily GitHub has their release system, for how to create releases see [instructions here][inst]

Thanks, and have a great day!

[inst]: <https://help.github.com/articles/creating-releases/>

**Comment by hackerb9** [comment]
Thanks for letting me know. I've now released v1.6.0.
